Revert one of our code changes to solve build errors
this change is introduced as part of commit

Release for Mainnet compatibility
https://github.com/gluwa/creditcoin-staking-dashboard/commit/444924858297de6a34d7c0c08e073556b5b4e6e6

without additional context. (It looks like this may have been a merge
commit and the context got lost).

After the rebase to latest upstream a variable which previously existed
and was used as part of the newly added code no longer exists:

src/library/ListItem/Labels/NominationStatus.tsx:31:22 - error TS2552: Cannot find name 'nominationStatus'. Did you mean 'NominationStatus'?

31     const isActive = nominationStatus === 'active';
                        ~~~~~~~~~~~~~~~~

Because the context is missing I have no idea what we're trying to do
here so revert to upstream's implementation.