Release for Mainnet compatibility (#82)
* Feature/ci

* made a docker image

* ignore yarn

* get rid of .yarn from commit

* lock changed

* docker compose

* azure devops ci

Co-authored-by: Thomas McDonald <mcdonald.thomas1284@gmail.com>

* Point Creditcoin Test to updated subscan domain

* Run CI jobs on PRs for dev

* Don't automatically close PRs as stale

* Fix height of the Recent Payouts widget

* Distinguish era 0 from era data unsynced

* Make `isPlaceholder` mandatory

* Remove broken subscan button from overview page

* Remove unused import

* Hide the "Mainnet" entry from the networks list to prevent tester (#12)

confusion

Co-authored-by: Ada <>

* Set TestNet as default

* Change text color on buttons from white to black (#14)

* Remove default filter excludes; Add community entry for Gluwa (#15)

* Make linter happy (#16)

* Remove Active Pools from Overview page (#17)

Co-authored-by: Ada <>

* Remove exclusion filters for validator selection methods (#18)

* Updated colors for Test and Dev networks (#19)

* Fix: Adjust fontSize, some colors / change the font-family, some svg (#20)

* Fix: Add paddingBottom to Balance section in Overview

* Fix incosistent filter behavior in validator list; Fix duplicates when
autogenerating validator list

* Fix support email in Gluwa Validator Identity

* [SS-170] Adjust margins on Nominate pages

* [SS-172] Change the title font-size on the Details page

* [SS-169] The color of text should be black with the background color of the button is #9CFFAA

* Remove Add Parachain Validator button

* Remove controller account deprecation warning

* Remove references to pools, ledger, and polkadot vault

* Resolve CSUB-581; Rebased on CSUB-580; Remove Locale Validation from CI'

* [SS-164] Remove h4 color setting

* [SS-173] Set default color

* [SS-173] Change default color setup

* [SS-174] Guage color changed

* [SS-173] Add support default address color

* Remove pools announcements from overview page

* Remove Devnet entry from Networks List

* Update branding per marketing

* prod build

* Delete OldDockerfile

* Remove staging dashboard URL, see

https://community.creditcoin.org/t/testnet-staking-dashboard-gone/751

https://gluwa.slack.com/archives/C02H93W9LLT/p1688020056679919

* Create codeql.yml

* Remove Dependabot auto-merge CI job

* Enable Pre-commit CI

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Use telemetry.creditcoin.network instead of polkadot.io

* Enable YAML check with Pre-commit CI

* Update CI config b/c of invalid job definition

validate-locales job has been removed in
7db5e488c611fc1db8a77f347b7bc7e89e16be3f and we can't depend on it

* Bump typescript from 5.0.4 to 5.1.6

Bumps [typescript](https://github.com/Microsoft/TypeScript) from 5.0.4 to 5.1.6.
- [Release notes](https://github.com/Microsoft/TypeScript/releases)
- [Commits](https://github.com/Microsoft/TypeScript/compare/v5.0.4...v5.1.6)

---
updated-dependencies:
- dependency-name: typescript
  dependency-type: direct:development
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump framer-motion from 10.12.16 to 10.12.18

Bumps [framer-motion](https://github.com/framer/motion) from 10.12.16 to 10.12.18.
- [Changelog](https://github.com/framer/motion/blob/main/CHANGELOG.md)
- [Commits](https://github.com/framer/motion/compare/v10.12.16...v10.12.18)

---
updated-dependencies:
- dependency-name: framer-motion
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump vite-bundle-visualizer from 0.7.0 to 0.8.0

Bumps [vite-bundle-visualizer](https://github.com/KusStar/vite-bundle-visualizer) from 0.7.0 to 0.8.0.
- [Commits](https://github.com/KusStar/vite-bundle-visualizer/compare/v0.7.0...v0.8.0)

---
updated-dependencies:
- dependency-name: vite-bundle-visualizer
  dependency-type: direct:development
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump vite-plugin-checker from 0.6.0 to 0.6.1

Bumps [vite-plugin-checker](https://github.com/fi3ework/vite-plugin-checker) from 0.6.0 to 0.6.1.
- [Release notes](https://github.com/fi3ework/vite-plugin-checker/releases)
- [Changelog](https://github.com/fi3ework/vite-plugin-checker/blob/main/CHANGELOG.md)
- [Commits](https://github.com/fi3ework/vite-plugin-checker/compare/vite-plugin-checker@0.6.0...vite-plugin-checker@0.6.1)

---
updated-dependencies:
- dependency-name: vite-plugin-checker
  dependency-type: direct:development
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump @substrate/connect from 0.7.26 to 0.7.30

Bumps [@substrate/connect](https://github.com/paritytech/substrate-connect) from 0.7.26 to 0.7.30.
- [Changelog](https://github.com/paritytech/substrate-connect/blob/main/DEPLOY-RELEASE.md)
- [Commits](https://github.com/paritytech/substrate-connect/commits)

---
updated-dependencies:
- dependency-name: "@substrate/connect"
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump @polkadot/util from 12.2.1 to 12.3.2

Bumps [@polkadot/util](https://github.com/polkadot-js/common/tree/HEAD/packages/util) from 12.2.1 to 12.3.2.
- [Release notes](https://github.com/polkadot-js/common/releases)
- [Changelog](https://github.com/polkadot-js/common/blob/master/CHANGELOG.md)
- [Commits](https://github.com/polkadot-js/common/commits/v12.3.2/packages/util)

---
updated-dependencies:
- dependency-name: "@polkadot/util"
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump i18next-browser-languagedetector from 7.0.2 to 7.1.0

Bumps [i18next-browser-languagedetector](https://github.com/i18next/i18next-browser-languageDetector) from 7.0.2 to 7.1.0.
- [Changelog](https://github.com/i18next/i18next-browser-languageDetector/blob/master/CHANGELOG.md)
- [Commits](https://github.com/i18next/i18next-browser-languageDetector/compare/v7.0.2...v7.1.0)

---
updated-dependencies:
- dependency-name: i18next-browser-languagedetector
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump @polkadot/react-identicon from 3.4.1 to 3.5.1

Bumps [@polkadot/react-identicon](https://github.com/polkadot-js/ui/tree/HEAD/packages/react-identicon) from 3.4.1 to 3.5.1.
- [Release notes](https://github.com/polkadot-js/ui/releases)
- [Changelog](https://github.com/polkadot-js/ui/blob/master/CHANGELOG.md)
- [Commits](https://github.com/polkadot-js/ui/commits/v3.5.1/packages/react-identicon)

---
updated-dependencies:
- dependency-name: "@polkadot/react-identicon"
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Reduce the frequency of Dependabot and don't jump to major versions

* Enable MegaLinter

* Apply eslint --fix to files outside src/

* Disable react/jsx-curly-brace-presence rule b/c it breaks builds

with this rule enabled we get

/home/runner/work/creditcoin-staking-dashboard/creditcoin-staking-dashboard/src/library/Headers/Connected.tsx
Error:   54:23  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
Error:   69:23  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence

and can't finish the build

* Comment out unused variable. Disabled in c643b252f

* Apply eslint --fix

* removed light client option from network selection

* updated src/library/Form/Unbond/UnbondFeedback.tsx to use the correct number of decimals in error messages

* renaming incorrect branches

* validator splits not correctly summing to total bonded amound in staking dashboard

* Run yarn list in CI

to dump the versions of installed packages for future reference

* eslint: disable import/order rule

because it produces lots of offences and fixing some of these offences
conflicts with the import ordering expected by prettier!

* Add a security policy

* re-added code to handle nomination pool case

updated NominationStatus.tsx to show the correct breakdown of bonded fund between validators

* added reset function that clears local storage and does a hard reload of the window location when the error boundary is broken

* Move subwallet to first position in connect menu; Update Subwallet icon

* Uncomment mainnet entry

* Update Mainnet entry to loadbalanced url

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Thomas McDonald <mcdonald.thomas1284@gmail.com>
Co-authored-by: Ada <>
Co-authored-by: Alex Todorov <alex.todorov@gluwa.com>
Co-authored-by: Ada <unknown>
Co-authored-by: Nathan Whitaker <17734409+nathanwhit@users.noreply.github.com>
Co-authored-by: Nathan Whitaker <nathan.whitaker01@gmail.com>
Co-authored-by: nbass3 <70085020+nbass3@users.noreply.github.com>
Co-authored-by: Hyeonggook Lee <hyeonggook.lee@gluwa.com>
Co-authored-by: Ada Anderson <ada.anderson@gluwa.com>
Co-authored-by: David Lebee <david.lebee@gluwa.com>
Co-authored-by: Alexander Todorov <atodorov@otb.bg>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Zachary Frederick <zach.frederick@gluwa.com>
Co-authored-by: Zach Frederick <zachfred62@gmail.com>